- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Build container
      docker_image: 
        path: "."
        docker_url: "{{ lookup('env', 'DOCKER_HOST') }}"
        name: ansible_base
        state: build

    - name: Run sshd for next step
      docker:
        name: ansible_target
        image: ansible_base
        docker_url: "{{ lookup('env', 'DOCKER_HOST') }}"
        #ports: 0.0.0.0:49099:22
        ports: 22
        command: /usr/sbin/sshd -D

    - name: Containers dump
      #debug: msg= "{{ inventory_hostname }} -> {{ item['HostConfig'] }}" 
      #debug: msg={{ item['Name'] }}:{{ item['HostConfig']['PortBindings']['22/tcp'][0]['HostPort'] }}
      debug: msg={{ item['Name'] }}
      with_items: docker_containers
